# Generated by Django 5.0.14 on 2026-09-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_reference',
            field=models.CharField(blank=True, help_text='eSewa transaction_uuid or Khalti pidx - used to match the callback', max_length=100),
        ),
        migrations.AddField(
            model_name='wallettopup',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wallettopup',
            name='gateway_reference',
            field=models.CharField(blank=True, help_text='eSewa transaction_uuid or Khalti pidx - used to match the callback', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('BANK', 'Bank Transfer')], default='ESEWA', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text="The gateway's own transaction ID once paid", max_length=100),
        ),
        migrations.AlterField(
            model_name='wallettopup',
            name='method',
            field=models.CharField(choices=[('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('BANK', 'Bank Transfer')], default='ESEWA', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettopup',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettopup',
            name='transaction_id',
            field=models.CharField(blank=True, help_text="The gateway's own transaction ID once paid", max_length=100),
        ),
    ]
