# Generated by Django 5.0.14 on 2026-09-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_failure_reason_payment_gateway_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformwallet',
            name='bank_account_name',
            field=models.CharField(blank=True, default='JobPlatform Pvt Ltd', max_length=150),
        ),
        migrations.AddField(
            model_name='platformwallet',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='platformwallet',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='platformwallet',
            name='esewa_id',
            field=models.CharField(blank=True, help_text="The platform's own eSewa ID (phone number), shown on manual top-up pages", max_length=20),
        ),
        migrations.AddField(
            model_name='platformwallet',
            name='khalti_id',
            field=models.CharField(blank=True, help_text="The platform's own Khalti ID (phone number)", max_length=20),
        ),
    ]
