# Generated by Django 5.0.14 on 2026-09-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_platformwallet_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformwallet',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text="Upload your real eSewa/Khalti/bank payment QR code (a photo or export from the eSewa/Khalti app, or your bank's QR). Shown on the manual top-up/payment pages instead of the auto-generated placeholder QR, so scanning it actually pays the right account.", null=True, upload_to='wallet_qr/'),
        ),
    ]
