# Generated by Django 5.0.14 on 2026-09-03 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NEW_JOB', 'New job posted'), ('NEW_APPLICATION', 'New application'), ('SELECTED', 'Selected for a job'), ('PAYMENT_SUCCESS', 'Payment received'), ('WALLET_TOPUP', 'Wallet topped up'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, help_text='Relative URL to open when clicked', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
